name: null

channels:
  - defaults
  - conda-forge

dependencies:
  - absl-py=0.8
  - astor=0.8
  - gast=0.2
  - google-pasta=0.1
  - grpcio=1.16
  - h5py=2.9
  - jupyterlab=1.1
  - keras-applications=1.0
  - keras-preprocessing=1.1
  - markdown=3.1
  - numpy=1.17
  - opt-einsum=3.0
  - pip=19.2
  - protobuf=3.9
  - pip:
    - tensorflow==2.0.0
  - python=3.6
  - termcolor=1.1
  - werkzeug=0.16
  - wrapt=1.11
